language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
install:
  - pip install codecov
  - pip install flake8 pep8-naming flake8-quotes
before_script:
  flake8 --max-line-length=99
script:
  python -Werror -m coverage run test.py
after_success:
  codecov